config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "other/index"

  get '/home/turbo_frame_form' => 'home#turbo_frame_form', as: 'turbo_frame_form'
  post '/home/turbo_frame_submit' => 'home#turbo_frame_submit', as: 'turbo_frame_submit'

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # @route GET /turbo_frame_form
  def turbo_frame_form

  end

  def turbo_frame_submit
    extracted_anynumber = params[:any][:anynumber]
    render :turbo_frame_form, status: :ok, locals: {anynumber: extracted_anynumber, comment: 'turbo_frame_submit ok' }

  end

end

app/controllers/other_controller.rb
class OtherController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>This is home</h1>
<div><%= link_to "go to other page", other_index_path %></div>

<%= turbo_frame_tag 'anyframe' do %>        
  <div>
    <h2>Home view</h2>
    <%= form_with scope: :any, url: turbo_frame_submit_path, local: true do |form| %>
      <%= form.label :anynumber, 'Type an integer (odd or even)', 'class' => 'my-0  d-inline'  %>
              <%= form.text_field :anynumber, type: 'number', 'required' => 'true', 'value' => "#{local_assigns[:anynumber] || 0}",  'aria-describedby' => 'anynumber' %>
                        <%= form.submit 'Submit this number', 'id' => 'submit-number' %>
                              
    <% end %>
  </div>
<% end %>

app/views/home/turbo_frame_form.html.erb
<section>

  <%= turbo_frame_tag 'anyframe' do %>

    <div>
      <h2>Frame view</h2>
      <%= form_with scope: :any, url: turbo_frame_submit_path, local: true do |form| %>
        <%= form.label :anynumber, 'Type an integer (odd or even)', 'class' => 'my-0  d-inline'  %>
        <%= form.text_field :anynumber, type: 'number', 'required' => 'true', 'value' => "#{local_assigns[:anynumber] || 0}",  'aria-describedby' => 'anynumber' %>
        <%= form.submit 'Submit this number', 'id' => 'submit-number' %>
      <% end %>

      <h2>Data of the view</h2>
      <pre style="font-size: .7rem;"><%= JSON.pretty_generate(local_assigns) %></pre> 
    </div>

  <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railshotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/other/index.html.erb
<h1>This is another page</h1>
<div><%= link_to "go to home page", root_path %></div>